name: Build Binaries

on:
  push:
    branches: [master] # Run on master or tags
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  build_x64_native:
    name: ${{ matrix.os }} Binaries
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - os: ubuntu
            runner: ubuntu-20.04
            output: linux
            testbin: linux-test
          - os: macos
            runner: macos-latest
            output: macos
            testbin: macos-test
          - os: windows
            runner: windows-latest
            output: windows.exe
            testbin: windows-test.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.2'

      - name: Compile x64 binary
        id: compile
        run: |
          cd stubs/
          go build -o ${{ matrix.output }} stub.go
          echo '' >> ${{ matrix.output }}
          echo '### CAXA ###' >> ${{ matrix.output }}

      - name: Test binary # Do a really simple smoke test of the stub binary
        id: test
        run: |
          cd stubs/
          cp ${{ matrix.output }} ${{ matrix.testbin }}
          echo 'success' > test.txt
          tar -czf - test.txt >> ${{ matrix.testbin }}
          printf "\n{ \"identifier\": \"${{ matrix.testbin }}/temp\", \"command\": [\"cat\", \"{{caxa}}/test.txt\"] }" >> ${{ matrix.testbin }}
          RESULT=$(./${{ matrix.testbin }} 2>&1)
          echo "RESULT=$RESULT" >> $GITHUB_ENV
          [ "$RESULT" = 'success' ] || exit 1

      - name: Test Results
        if: failure()
        run: |
          echo "${{ matrix.os }} binary test failed:"
          echo ${{ env.RESULT }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: "stubs/${{ matrix.output }}"

  build_arm:
    name: ${{ matrix.arch }} Binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [linux/arm/v7, linux/arm64/v8]
        include:
          - platform: linux/arm/v7
            arch: arm32v7
            output: linux-armv7
            testbin: linux-armv7-test
          - platform: linux/arm64/v8
            arch: arm64v8
            output: linux-arm64
            testbin: linux-arm64-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Enable Docker Experimental Features
        run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
  
      - name: Build ${{ matrix.arch }}
        run: |
          cd stubs
          docker run --rm --platform ${{ matrix.platform }} -v "$PWD":/usr/src/myapp -w /usr/src/myapp ${{ matrix.arch }}/golang:1.16 sh -c  "go build -o ${{ matrix.output }} stub.go && echo >> ${{ matrix.output }} && echo '### CAXA ###' >> ${{ matrix.output }}"

      - name: Test binary # Do a really simple smoke test of the stub binary
        id: test
        run: |
          cd stubs/
          cp ${{ matrix.output }} ${{ matrix.testbin }}
          echo 'success' > test.txt
          tar -czf - test.txt >> ${{ matrix.testbin }}
          printf "\n{ \"identifier\": \"${{ matrix.testbin }}/temp\", \"command\": [\"cat\", \"{{caxa}}/test.txt\"] }" >> ${{ matrix.testbin }}
          RESULT=$(docker run --rm --platform ${{ matrix.platform }} -v "$PWD":/usr/src/myapp -w /usr/src/myapp ${{ matrix.arch }}/golang:1.16 sh -c  "./${{ matrix.testbin }} 2>&1")
          echo "RESULT=$RESULT" >> $GITHUB_ENV
          [ "$RESULT" = 'success' ] || exit 1

      - name: Test Results
        if: failure()
        run: |
          echo "${{ matrix.os }} binary test failed:"
          echo ${{ env.RESULT }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: "stubs/${{ matrix.output }}"

  job_upload:
    name: Upload Release Assets
    needs: [build_x64_native, build_arm]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: File Hashes
        run: |
          cd stubs/
          md5sum * > md5sums.txt
          cat md5sums.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux
            linux-arm64
            linux-armv7
            macos
            windows.exe
            md5sums.txt
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: true
      #     prerelease: false

      # # We have to upload assets individually using upload-release-asset@v1
      # # There isn't a matrix for steps.
      # - name: Upload md5sums
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/md5sums.txt
      #     asset_name: md5sums.txt
      #     asset_content_type: text

      # - name: Upload Linux Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/linux
      #     asset_name: linux
      #     asset_content_type: application/zip

      # - name: Upload MacOS Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/macos
      #     asset_name: macos
      #     asset_content_type: application/zip

      # - name: Upload Windows Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/windows.exe
      #     asset_name: windows.exe
      #     asset_content_type: application/zip

      # - name: Upload Linux armv7 Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/linux-armv7
      #     asset_name: linux-armv7
      #     asset_content_type: application/zip

      # - name: Upload Linux arm64 Release
      #   if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
      #     asset_path: ./stubs/linux-arm64
      #     asset_name: linux-arm64
      #     asset_content_type: application/zip
